/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package campus_project;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amanj
 */
public class ElegiblityCheck extends javax.swing.JFrame {

    /**
     * Creates new form ElegiblityCheck
     */
    public ElegiblityCheck() {
        setTitle("Eligiblity Check List");
        setLocation(500,200);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 255, 204));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Roll No", "First_name", "Last_name", "X", "XII", "UG", "PG"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 610, 270));

        jToggleButton2.setBackground(new java.awt.Color(0, 204, 204));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton2.setText("Show All ");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(0, 204, 204));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton1.setText("X , XII < 60 %");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jToggleButton3.setBackground(new java.awt.Color(0, 204, 204));
        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton3.setText("UG < 60 %");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 111, -1));

        jToggleButton4.setBackground(new java.awt.Color(0, 204, 204));
        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton4.setText("PG < 60 %");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 106, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("No at all Elegible ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jToggleButton5.setBackground(new java.awt.Color(0, 204, 204));
        jToggleButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton5.setText("Print");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campus_project/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/campus","root","");
            Statement st = con.createStatement();
            
            String q,Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc;
            
            q = "SELECT `Rno`, `First_Name`, `Last_Name`, `X`, `XII`, `Grad_Perc`, `PostGrad_Perc` FROM student;";
            ResultSet rs2 = st.executeQuery(q);
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs2.next())
            {
                Rno =  rs2.getString("Rno");
                First_Name = rs2.getString("First_Name");
                Last_Name = rs2.getString("Last_Name");
                X = rs2.getString("X");
                XII = rs2.getString("XII");
                Grad_Perc = rs2.getString("Grad_Perc");
                PostGrad_Perc = rs2.getString("PostGrad_Perc");       
       
                String data[] = {Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc};
                df.addRow(data);
            }        
    }                                           
     catch(ClassNotFoundException | SQLException e)
     {
         
     }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/campus","root","");
            Statement st = con.createStatement();
            
            String q,Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc;
            
            q = "SELECT `Rno`, `First_Name`, `Last_Name`, `X`, `XII`, `Grad_Perc`, `PostGrad_Perc` FROM student where X and XII < 60";
            ResultSet rs2 = st.executeQuery(q);
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs2.next())
            {
                Rno =  rs2.getString("Rno");
                First_Name = rs2.getString("First_Name");
                Last_Name = rs2.getString("Last_Name");
                X = rs2.getString("X");
                XII = rs2.getString("XII");
                Grad_Perc = rs2.getString("Grad_Perc");
                PostGrad_Perc = rs2.getString("PostGrad_Perc");      
               
                String data[] = {Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc};
                df.addRow(data);
            }        
    }                                           
     catch(ClassNotFoundException | SQLException e)
     {
         
     }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
     try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/campus","root","");
            Statement st = con.createStatement();
            
            String q,Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc;
            
            q = "SELECT `Rno`, `First_Name`, `Last_Name`, `X`, `XII`, `Grad_Perc`, `PostGrad_Perc` FROM student where Grad_Perc < 60";
            ResultSet rs2 = st.executeQuery(q);
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs2.next())
            {
                Rno =  rs2.getString("Rno");
                First_Name = rs2.getString("First_Name");
                Last_Name = rs2.getString("Last_Name");
                X = rs2.getString("X");
                XII = rs2.getString("XII");
                Grad_Perc = rs2.getString("Grad_Perc");
                PostGrad_Perc = rs2.getString("PostGrad_Perc");       
       
                String data[] = {Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc};
                df.addRow(data);
            }        
    }                                           
     catch(ClassNotFoundException | SQLException e)
     {
         
     }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed

        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/campus","root","");
            Statement st = con.createStatement();
            
            String q,Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc;
            
            q = "SELECT `Rno`, `First_Name`, `Last_Name`, `X`, `XII`, `Grad_Perc`, `PostGrad_Perc` FROM student where PostGrad_Perc < 60";
            ResultSet rs2 = st.executeQuery(q);
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs2.next())
            {
                Rno =  rs2.getString("Rno");
                First_Name = rs2.getString("First_Name");
                Last_Name = rs2.getString("Last_Name");
                X = rs2.getString("X");
                XII = rs2.getString("XII");
                Grad_Perc = rs2.getString("Grad_Perc");
                PostGrad_Perc = rs2.getString("PostGrad_Perc");       
       
                String data[] = {Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc};
                df.addRow(data);
            }        
    }                                           
     catch(ClassNotFoundException | SQLException e)
     {
         
     }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/campus","root","");
            Statement st = con.createStatement();
            
            String q,Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc;
            
            q = "SELECT `Rno`, `First_Name`, `Last_Name`, `X`, `XII`, `Grad_Perc`, `PostGrad_Perc` FROM student where X AND XII And Grad_Perc AND PostGrad_Perc < 60";
            ResultSet rs2 = st.executeQuery(q);
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs2.next())
            {
                Rno =  rs2.getString("Rno");
                First_Name = rs2.getString("First_Name");
                Last_Name = rs2.getString("Last_Name");
                X = rs2.getString("X");
                XII = rs2.getString("XII");
                Grad_Perc = rs2.getString("Grad_Perc");
                PostGrad_Perc = rs2.getString("PostGrad_Perc");       
       
                String data[] = {Rno,First_Name,Last_Name,X,XII,Grad_Perc,PostGrad_Perc};
                df.addRow(data);
            }        
    }                                           
     catch(ClassNotFoundException | SQLException e)
     {
         
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH);

        } catch (PrinterException e) {
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegiblityCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegiblityCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegiblityCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegiblityCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegiblityCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
